#services:
#  mongodb:
#    image: 'mongodb/mongodb-community-server:latest'
#    environment:
#      - 'MONGO_INITDB_DATABASE=mydatabase'
#      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
#      - 'MONGO_INITDB_ROOT_USERNAME=root'
#    ports:
#      - '27017'
#  redis:
#    image: 'redis:latest'
#    ports:
#      - '6379'

services:
