server:
  port: 4000
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
  docker:
    compose:
      enabled: false
  application:
    name: SpringBoot
  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      uri: mongodb://localhost:27017/spring
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: harnooraulakh16@gmail.com
    password: ${SMTP_PASS:default}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


cloudinary:
  cloud_name: "dflt5h4eh"
  api_key: "855368213215438"
  api_secret: "aIy4-5LHskJLBVPguu09nlWcQ_A"
